### ISSUE TITLE
Adding new types to a Union should be backwards compatible

### ISSUE THREAD

**Issue by danpalmer** [jarwol/graphql-schema-utils#10]
Given that GraphQL's type/interface matching syntax provides powerful control over the format of returned data, I believe adding types to a GraphQL Union should be considered backwards compatible.

I could see the option for adding a strict mode where this case, and potentially also the addition of new values to enums, are considered backwards incompatible, but with the affordances given by GraphQL'- structure, semantics, and syntax, I believe the default behaviour here should be to be backwards compatible.

**Comment by jarwol** [comment]
Yeah I agree adding types to a Union should be backwards compatible. Update incoming.

**Comment by danpalmer** [comment]
Thanks for this!
