### ISSUE TITLE
Incorrectly detected backwards compatibility

### ISSUE THREAD

**Issue by danpalmer** [jarwol/graphql-schema-utils#8]
> Field type changed on field MarkAllIdeasAsSeenInput.ideaIds from : `"[ID!]!"` to `"[ID!]"`.

I just got this output from some tooling that we use built around `graphql-schema-utils`. To my understanding, an input field changing from required to not-required is a backwards compatible change, so this looks like a bug.

Could you confirm whether this is expected or not, am I missing details about backwards compatibility here?

**Comment by jarwol** [comment]
Sorry for the delay on this. I agree with you that this should be a backward compatible change. I've added some tests and fixed this scenario. Thanks for the heads up!
